name: SAST

on:
  # Trigger the workflow manually
  workflow_dispatch:
  
  schedule: 
  - cron: "0 23 * * 5"

jobs:
  checkmarx:
    name: checkmarx
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # updated checkout to v4

      - name: Checkmarx CxFlow Action
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.9
        with:
          checkmarx_url: https://cxprivatecloud.checkmarx.net
          checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }}
          checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
          checkmarx_client_secret: 014DF517-39D1-4453-B7B3-9930C563627C
          team: CxServer/SP/APAC # Their team format is wrong
          incremental: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project: 'Basecone-Backend-Core'
          params: --cx-flow.zip-exclude=\.git/.*,\.github/.*,src/Infrastructure.Data.Master/Migrations/.* #no single quotes required
